name: Update Documentation
on:
  push:
    branches:
      - main


jobs:
  update_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and static website
        run: |
          cd website
          yarn install
          yarn build
      - name: Push to Github Pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./publish.sh
